### ISSUE TITLE
Set everyone to "away" at night

### ISSUE THREAD

**Issue by voodoocode** [talentsconnect/awayboard#8]
All tiles could be set to "away" at night, as lazy people might forget that before calling it a day.

Time of that action should be configurable (e.g. env var).

**Comment by foretspaisibles** [comment]
Maybe we could interface the awayboard with the team calendar? Provided the team calendar is up to date.

Otherwise I don't think it's correct to put everyone in the “column” because it would display an information that is not accurate – so we don'y know if Harald is actually away or just did not update its tile.  Maybe a “don't know/limbo” column would be more appropriate? This relates to #4.

**Comment by voodoocode** [comment]
I agree that setting to "away" is possibly wrong.
A calendar API will also bring incorrect states , as no one updates that, when they are ill at home.

I'm closing this one, might follow the idea of a new "unknown" status column.
